STATE_DATA = {
    "AK": {"mod": 0.20,  "label": "Alaska",          "reg": "Remote / high-altitude — significant cost uplift"},
    "AL": {"mod": -0.05, "label": "Alabama",          "reg": "Gulf Coast — moderate O&G infrastructure"},
    "AR": {"mod": -0.10, "label": "Arkansas",         "reg": "Gulf Coast — established O&G infrastructure"},
    "AZ": {"mod": 0.05,  "label": "Arizona",          "reg": "Southwest — limited geothermal infrastructure"},
    "CA": {"mod": -0.15, "label": "California",       "reg": "NV/UT/ID/CA — established geothermal province"},
    "CO": {"mod": 0.00,  "label": "Colorado",         "reg": "CO/WY — mixed terrain, baseline costs"},
    "FL": {"mod": 0.05,  "label": "Florida",          "reg": "Southeast — limited geothermal potential"},
    "GA": {"mod": 0.05,  "label": "Georgia",          "reg": "Southeast — limited geothermal data"},
    "HI": {"mod": 0.15,  "label": "Hawaii",           "reg": "Island logistics — cost uplift"},
    "ID": {"mod": -0.15, "label": "Idaho",            "reg": "NV/UT/ID/CA — established geothermal province"},
    "IL": {"mod": -0.05, "label": "Illinois",         "reg": "Mid-continent — moderate O&G infrastructure"},
    "IN": {"mod": -0.05, "label": "Indiana",          "reg": "Mid-continent — moderate O&G infrastructure"},
    "KS": {"mod": -0.05, "label": "Kansas",           "reg": "Mid-continent — moderate O&G infrastructure"},
    "KY": {"mod": -0.05, "label": "Kentucky",         "reg": "Appalachian — established O&G infrastructure"},
    "LA": {"mod": -0.10, "label": "Louisiana",        "reg": "Gulf Coast — established O&G infrastructure"},
    "MI": {"mod": 0.00,  "label": "Michigan",         "reg": "Mid-continent — moderate O&G infrastructure"},
    "MN": {"mod": 0.00,  "label": "Minnesota",        "reg": "Mid-continent — baseline costs"},
    "MO": {"mod": 0.00,  "label": "Missouri",         "reg": "Mid-continent — baseline costs"},
    "MS": {"mod": -0.10, "label": "Mississippi",      "reg": "Gulf Coast — established O&G infrastructure"},
    "MT": {"mod": 0.10,  "label": "Montana",          "reg": "Northern Rockies — remote / mixed federal land"},
    "ND": {"mod": -0.05, "label": "North Dakota",     "reg": "Mid-continent — moderate O&G infrastructure"},
    "NE": {"mod": 0.00,  "label": "Nebraska",         "reg": "Mid-continent — baseline costs"},
    "NM": {"mod": 0.00,  "label": "New Mexico",       "reg": "Southwest — moderate infrastructure"},
    "NV": {"mod": -0.15, "label": "Nevada",           "reg": "NV/UT/ID/CA — established geothermal province"},
    "NY": {"mod": 0.05,  "label": "New York",         "reg": "Northeast — limited geothermal infrastructure"},
    "OH": {"mod": -0.05, "label": "Ohio",             "reg": "Appalachian — established O&G infrastructure"},
    "OK": {"mod": -0.10, "label": "Oklahoma",         "reg": "TX/OK — established O&G infrastructure"},
    "OR": {"mod": 0.00,  "label": "Oregon",           "reg": "Pacific Northwest — moderate infrastructure"},
    "PA": {"mod": -0.05, "label": "Pennsylvania",     "reg": "Appalachian — established O&G infrastructure"},
    "SD": {"mod": 0.00,  "label": "South Dakota",     "reg": "Mid-continent — baseline costs"},
    "TX": {"mod": -0.10, "label": "Texas",            "reg": "TX/OK — established O&G infrastructure"},
    "UT": {"mod": -0.15, "label": "Utah",             "reg": "NV/UT/ID/CA — established geothermal province"},
    "VA": {"mod": 0.00,  "label": "Virginia",         "reg": "Appalachian — limited geothermal data"},
    "WA": {"mod": 0.00,  "label": "Washington",       "reg": "Pacific Northwest — moderate infrastructure"},
    "WV": {"mod": -0.05, "label": "West Virginia",    "reg": "Appalachian — established O&G infrastructure"},
    "WY": {"mod": 0.00,  "label": "Wyoming",          "reg": "CO/WY — mixed terrain, baseline costs"},
    "OTHER": {"mod": 0.00, "label": "Other / Unknown", "reg": "Baseline costs applied"},
}

DEPTH_ZONES = [
    {"max": 500,  "label": "Very shallow — heat flow / TG wells only",        "dm": 0.5},
    {"max": 1500, "label": "Shallow-intermediate — slim-hole coring range",   "dm": 0.8},
    {"max": 2500, "label": "Intermediate — standard slim-hole coring",        "dm": 1.0},
    {"max": 3500, "label": "Deep — approaching full-size well costs",         "dm": 1.6},
    {"max": 4500, "label": "Very deep — full-size well costs apply",          "dm": 2.5},
    {"max": 5000, "label": "Extreme depth — frontier EGS territory",          "dm": 4.0},
]

PLAYS = {
    "sed": {
        "label": "Sedimentary EGS", "sub": "Intracratonic basin",
        "ex": "Anadarko Basin (OK/TX), Williston Basin (ND)",
        "ph12lo": 1.5, "ph12hi": 5.6, "ph3lo": 1.5, "ph3hi": 9.7, "flo": 0.72, "fhi": 6.8,
        "ph12d": "12–22 months", "ph3d": "8–14 months", "totd": "18–34 months",
        "crit": "2D seismic interpretation + NEPA",
        "hfw": 7, "shw": 3,
        "drv": "O&G data + 2D seismic + stress field → heat flow wells + slim-hole coring",
        "ft": "Geological mapping + ground gravity + ground magnetics + MT regional + MT detailed + MT polarization + 3D seismic (if warranted) + diagenesis investigation",
        "col": "#1D9E75", "coll": "#E1F5EE",
        "notes": [
            "O&G well data (BHT, logs, production) is the highest-value free dataset.",
            "2D seismic interpretation is the long-pole on Ph.1+2 timeline.",
            "MT and geological mapping are Frequent — include if budget allows.",
            "BOP surface equipment needed — NOT included in cost estimate.",
            "Consortium priority: Formation Tops, Produced Water Chemistry, Lost Circulation Zones, Wellhead Temperatures.",
        ],
    },
    "hyb": {
        "label": "Hybrid EGS", "sub": "Orogenic belt / foreland",
        "ex": "Denver Basin (CO), Powder River Basin (WY)",
        "ph12lo": 2.4, "ph12hi": 10.1, "ph3lo": 1.2, "ph3hi": 8.2, "flo": 0.72, "fhi": 2.3,
        "ph12d": "14–26 months", "ph3d": "7–12 months", "totd": "20–38 months",
        "crit": "3D seismic interpretation + NEPA",
        "hfw": 4, "shw": 3,
        "drv": "O&G data + 2D seismic + 3D seismic (dominant pre-drill cost) + stress field → heat flow wells + slim-hole coring",
        "ft": "Geological mapping + ground gravity + ground magnetics + MT regional + MT detailed + MT polarization + diagenesis investigation",
        "col": "#378ADD", "coll": "#E6F1FB",
        "notes": [
            "3D seismic is the dominant pre-drill cost — evaluate necessity carefully.",
            "O&G data + 2D seismic provide basin framework before 3D decision.",
            "BOP surface equipment needed — NOT included in cost estimate.",
            "Consortium priority: Formation Tops, Fracture Gradient (DFIT), Lost Circulation Zones, Reservoir Pressures.",
        ],
    },
    "cry": {
        "label": "Crystalline EGS", "sub": "Basement / pure EGS",
        "ex": "Fervo Project Red (NV), FORGE Milford (UT)",
        "ph12lo": 0.825, "ph12hi": 3.0, "ph3lo": 1.0, "ph3hi": 6.7, "flo": 0.3, "fhi": 9.7,
        "ph12d": "10–18 months", "ph3d": "6–12 months", "totd": "14–28 months",
        "crit": "MT 3D inversion + NEPA",
        "hfw": 5, "shw": 2,
        "drv": "MT + MT polarization + geomechanical modelling → slim-hole coring for rock mechanics",
        "ft": "InSAR + geological mapping + ground gravity + ground magnetics + passive seismic + 2D seismic (if structural complexity) + 3D seismic (if structural complexity)",
        "col": "#E24B4A", "coll": "#FCEBEB",
        "notes": [
            "MT 3D inversion is the critical long-pole for Ph.1+2 timeline.",
            "Geomechanical modelling is ESSENTIAL before any drilling decision.",
            "Limited O&G well data — acquire stress and fracture data independently.",
            "Slim-hole coring critical for rock mechanics before full-size well.",
            "Consortium value lower — focus on USGS/academic sources.",
        ],
    },
}

TECHNIQUES = [
    {"name": "Literature review & GIS database",                              "ph": "Ph.1", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$15k–$80k"},
    {"name": "Existing O&G / mining / hydro well data",                       "ph": "Ph.1", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "Low / free"},
    {"name": "Environmental baseline data (NEPA monitoring)",                  "ph": "Ph.1", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$80k–$400k"},
    {"name": "Permitting & regulatory compliance (NEPA, BLM/USFS, state, tribal)", "ph": "Ph.1", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$200k–$800k"},
    {"name": "InSAR – Interferometric SAR (Sentinel-1)",                      "ph": "Ph.1", "sed": "Optional",  "hyb": "Optional",  "cry": "Frequent",  "cu": "$10k–$60k/proj"},
    {"name": "Multispectral & hyperspectral satellite imagery",                "ph": "Ph.1", "sed": "Rarely",    "hyb": "Rarely",    "cry": "Rarely",    "cu": "$5k–$40k"},
    {"name": "Structural geology / fault & fracture mapping",                  "ph": "Ph.2", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "incl. in mapping"},
    {"name": "Rock sampling & lab analysis",                                   "ph": "Ph.2", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$200–$2k/sample"},
    {"name": "Regional & detailed geological mapping",                         "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Frequent",  "cu": "$500–$2k/km²"},
    {"name": "Diagenesis investigation",                                       "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Optional",  "cu": "specialist"},
    {"name": "Stress field estimate (geological)",                             "ph": "Ph.2", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$10k–$40k"},
    {"name": "Geomechanical modelling (EGS)",                                  "ph": "Ph.2", "sed": "Optional",  "hyb": "Optional",  "cry": "Essential", "cu": "$50k–$200k"},
    {"name": "Ground gravity survey",                                          "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Frequent",  "cu": "$200–$800/station"},
    {"name": "Ground magnetic survey",                                         "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Frequent",  "cu": "$80–$400/station"},
    {"name": "Magnetotelluric (MT) – regional / detailed",                     "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Essential", "cu": "$3k–$8k/station"},
    {"name": "MT polarization (fracture orientation)",                         "ph": "Ph.2", "sed": "Frequent",  "hyb": "Frequent",  "cry": "Essential", "cu": "incl. in MT"},
    {"name": "2D seismic reflection",                                          "ph": "Ph.2", "sed": "Essential", "hyb": "Essential", "cry": "Frequent",  "cu": "$15k–$50k/line-km"},
    {"name": "3D seismic reflection",                                          "ph": "Ph.2", "sed": "Frequent",  "hyb": "Essential", "cry": "Frequent",  "cu": "$50k–$180k/km²"},
    {"name": "Passive seismic / ambient noise tomography",                     "ph": "Ph.2", "sed": "Rarely",    "hyb": "Rarely",    "cry": "Optional",  "cu": "$3k–$10k/station"},
    {"name": "TDEM (static-shift correction)",                                 "ph": "Ph.2", "sed": "Optional",  "hyb": "Optional",  "cry": "Optional",  "cu": "+$300–$800/station"},
    {"name": "AMT / broadband EM (<500 m)",                                    "ph": "Ph.2", "sed": "Rarely",    "hyb": "Rarely",    "cry": "—",         "cu": "$2k–$7k/station"},
    {"name": "Temp gradient / heat flow wells (<500 m)",                       "ph": "Ph.3", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$100k–$500k/well"},
    {"name": "Thermal conductivity measurements",                              "ph": "Ph.3", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$500–$2k/sample"},
    {"name": "Numerical conductive heat flow model",                           "ph": "Ph.3", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$20k–$100k"},
    {"name": "Slim-hole diamond core drilling (wireline coring)",              "ph": "Ph.3", "sed": "Essential", "hyb": "Essential", "cry": "Essential", "cu": "$250k–$2M/well"},
]

DATA_ITEMS = [
    {"name": "Bottom Hole Temperature (BHT)",                    "cat": "A1", "rel": "Geosciences", "desc": "Required in all major O&G states. Available in TX RRC, CA DOC, CO ECMC, UT DNR, WV DEP."},
    {"name": "Well Logs (Wireline / LWD)",                       "cat": "A1", "rel": "Geosciences", "desc": "Required in most states. Available after confidentiality period (6m–2yr)."},
    {"name": "Directional Surveys",                              "cat": "A1", "rel": "Geosciences", "desc": "Required in most states for deviated/horizontal wells."},
    {"name": "Production Flow Rates (Monthly)",                  "cat": "A1", "rel": "Production",  "desc": "Required and available in all major O&G states — TX RRC, CalGEM, CO ECMC, WV DEP, UT DNR."},
    {"name": "Injection Flow Rates",                             "cat": "A1", "rel": "Production",  "desc": "Required for Class II UIC wells. Public in TX RRC, CO ECMC, USEPA UIC database."},
    {"name": "Casing Records",                                   "cat": "A1", "rel": "Completions", "desc": "Required and available in state DBs via well completion reports."},
    {"name": "Perforation & Stimulation Data (FracFocus)",       "cat": "A1", "rel": "Completions", "desc": "Required via FracFocus in TX, CO, CA, WV, UT. Public and queryable."},
    {"name": "Formation Tops (Pick Data)",                       "cat": "A2", "rel": "Geosciences", "desc": "Required but NOT consistently in state DBs — often buried in PDFs. High-value gap."},
    {"name": "Produced Water Chemistry",                         "cat": "A2", "rel": "Geosciences", "desc": "Some states require reporting (EPA Class II UIC). Inconsistent digitization."},
    {"name": "Wellhead Temperature (WHT)",                       "cat": "A2", "rel": "Production",  "desc": "Required in production test reports but rarely structured/queryable. Major data gap."},
    {"name": "Wellhead Pressures (FWHP & SIWHP)",               "cat": "A2", "rel": "Production",  "desc": "Required in well test reports in many states. Not consistently digitized."},
    {"name": "Cementing Records",                                "cat": "A2", "rel": "Completions", "desc": "Required but detailed CBL quality data not consistently structured in state DBs."},
    {"name": "Lease Bonus & Royalty Rate",                       "cat": "A2", "rel": "Economics",   "desc": "Technically public in county deed records but NOT in structured DBs."},
    {"name": "P&A Bond / Regulatory Obligation",                 "cat": "A2", "rel": "Economics",   "desc": "Required by all states but often not easy to query."},
    {"name": "Geological Maps & Cross Sections",                 "cat": "B",  "rel": "Geosciences", "desc": "Not required. Regional maps from USGS/state surveys. Operator interpretations shareable in consortium."},
    {"name": "Core Analysis (Porosity & Permeability)",          "cat": "B",  "rel": "Geosciences", "desc": "NOT required. Operators would share anonymized in consortium."},
    {"name": "Gravity & Magnetic Surveys",                       "cat": "B",  "rel": "Geosciences", "desc": "Regional data from USGS/NGS. Operator high-res surveys shareable in consortium."},
    {"name": "MT / ERT / CSEM Surveys",                         "cat": "B",  "rel": "Geosciences", "desc": "Not required. Rarely acquired by O&G; shareable when acquired."},
    {"name": "Heat Flow / Temperature Gradient Maps",            "cat": "B",  "rel": "Geosciences", "desc": "Not required. Built from public BHT data. Operator-built interpretations shareable."},
    {"name": "Lost Circulation Zones (LCZs)",                   "cat": "B",  "rel": "Drilling",    "desc": "NOT required. Extremely valuable — indicates natural fractures. Operators would share anonymized."},
    {"name": "Mud Weight & Drilling Fluid Properties",           "cat": "B",  "rel": "Drilling",    "desc": "Not required. Shareable for pore pressure calibration."},
    {"name": "Drill Bit Data & Performance",                     "cat": "B",  "rel": "Drilling",    "desc": "Not required. Operators would share anonymized ROP data."},
    {"name": "Basin-Level Aggregate Production",                 "cat": "B",  "rel": "Production",  "desc": "Partially public via SEC 10-K/10-Q. Operators would share anonymized basin profiles."},
    {"name": "Reservoir Pressures (Pr, Pwf, Pws)",              "cat": "B",  "rel": "Production",  "desc": "NOT required publicly. Operators would share anonymized reservoir pressure profiles."},
    {"name": "Interference Testing / Frac Hits",                 "cat": "B",  "rel": "Production",  "desc": "NOT required. Valuable for hydraulic connectivity. Shareable anonymized."},
    {"name": "Fracture Gradient & DFIT Data",                    "cat": "B",  "rel": "Completions", "desc": "NOT required in most states. Operators would share aggregated frac gradient profiles."},
    {"name": "Frac Plug Type & Drillout Data",                   "cat": "B",  "rel": "Completions", "desc": "NOT required. Dissolvable plug temperature data relevant for geothermal."},
    {"name": "Water Handling & Disposal Cost",                   "cat": "B",  "rel": "Economics",   "desc": "Market-driven. Relevant to geothermal brine handling. Operators would share anonymized."},
    {"name": "LOE — Field/Basin Level",                          "cat": "B",  "rel": "Economics",   "desc": "Partially public via SEC 10-K/10-Q. Basin-level aggregated shareable."},
    {"name": "Basin/Field-Level CapEx (D&C)",                    "cat": "B",  "rel": "Economics",   "desc": "Disclosed at basin level in SEC filings. Useful for benchmarking well costs by depth."},
    {"name": "Geomechanical Data (Stress Field)",                "cat": "C",  "rel": "Geosciences", "desc": "NEVER required. Core EGS competitive intelligence. Must acquire independently."},
    {"name": "Seismic Data (2D & 3D Proprietary)",               "cat": "C",  "rel": "Geosciences", "desc": "Most competitive G&G asset. Operators will NOT share."},
    {"name": "Reservoir Fluid Chemistry",                        "cat": "C",  "rel": "Geosciences", "desc": "Proprietary. Operators will NOT share."},
    {"name": "Daily Drilling Reports (Full DDRs)",               "cat": "C",  "rel": "Drilling",    "desc": "Never public. Full operational detail. Will NOT share."},
    {"name": "Detailed Stimulation Design (Stage-by-Stage)",     "cat": "C",  "rel": "Completions", "desc": "Core completion engineering IP. Will NOT share."},
    {"name": "Total Well Cost — AFE vs. Actual",                 "cat": "C",  "rel": "Economics",   "desc": "Reveals efficiency benchmarks. Will NOT share."},
    {"name": "Well Economics Model (NPV, IRR)",                  "cat": "C",  "rel": "Economics",   "desc": "NEVER public. Most sensitive economic document. Will NOT share."},
]
